Todoer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = 'web'
urlpatterns = [
    path('', index_view, name='index'),

    path('register/',   register_view, name='register'),
    path('login/',      login_view, name='login'),
    path('logout/',     logout_view, name='logout'),
    path('active/', active_view, name='active' ),

    path('tasks/', tasks_view, name='tasks'),
    path('tasks/add/',    taskAdd_view, name='taskAd'),
    path('tasks/<int:id>/', taskShow_view, name='taskShow'),
    path('tasks/edit/<int:id>', taskEdit_view, name='taskEdit'),
    path('tasks/delete/<int:id>', taskDelete_view, name='taskDelete'),
    path('tasks/deleteConfirm/<int:id>', taskDeleteConfirm_view, name='taskDeleteConfirm'),
]

web/templates/active.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <title> Account activition </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <h1>{{ message }}</h1>
    <div class="content">
          <form action="">{% csrf_token %}
            <div class="button">
                <a href="/login/"><input type="button" value="Login"></a>
              </div>
              <div class="button">
                <a href="/"><input type="button" value="Go Back"></a>
              </div>
        </form>
    </div>
  </div>

</body>
</html>

web/templates/deleteConfirm.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Confirm Delete </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="title">Are you sure you want to delete this task?</div>
    <h1>{{ message }}</h1>
    <div class="content">
          <form action="{{ task.get_delete_url }}" method="POST">{% csrf_token %}
            <div class="button">
              <input type="submit" value="Delete task">
            </div>
            <div class="button">
                <a href="{{ task.get_url }}"><input type="button" value="Go Back"></a>
              </div>
        </form>
    </div>
  </div>

</body>
</html>

web/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title> Lets be orgnized </title>
    {% load static %}
    <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css" >
     
   </head>
<body>
  <div class="container">
    <div class="title">
        {% if user.username %}
        Welcome {{ user.username }}
        {% else %}
        We are todoer
        {% endif %}
    </div>
    <h3>{{ message }}</h3>
    <div class="content">
        
        <div class="user-details" style="margin-top: 15px;">
            <p>With todoer you can simply keep up with your tasks.
              <br><br><br>
              this project is under heavy development. right now we are working on
              send verfication sms part of the project. it is done but we have to wait
              for the paperworks. till then contact me for verfication code.
              <br><br><br>
              you can contact me via: +989171878751
              <br><br><br>
              also this project is open source and you can find it on github. make sure
              to commit and send issues so we can make it better.
              <br><br><br>
              <h1>NEWS:</h1>
              <br><br><br>
            </p>
            <table>
              <thead>
                  <tr>
                      <th>Title</th>
                      <th>Text</th>
                  </tr>
                  
              </thead>
              {% for new in news %}
              <tbody>
                  <tr>
                      <td>{{ new.title }}</td>
                      <td>{{ new.text }}</td>
                  </tr>
              </tbody>
                  {% endfor %}
          </table>
          </div>
          {% if request.user.is_anonymous %}
          <div class="button-container">
              <a href="{% url 'web:register' %}">
        <div class="button">
          <input type="button" value="register">
        </a>
        </div>
        <a href="{% url 'web:login' %}">
        <div class="button">
          <input type="button" value="Login">
        </a>
        </div>
    </div>
          {% elif not request.user.is_anonymous %}
          <form action="">{% csrf_token %}
            <div class="button">
              <a href="{% url 'web:logout' %}"><input type="button" value="Logout"></a>
            </div>
            <div class="button">
              <a href="{% url 'web:tasks' %}"><input type="button" value="Tasks"></a>
            </div>
          </form>
          {% endif %}
    </div>
  </div>

</body>
</html>

web/templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Login </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="title">Login</div>
    <h3>{{ message }}</h3>
    <div class="content">
        
      <form action="." method="POST">{% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">Username or Email</span>
            <input type="text" placeholder="Enter your username or email" name="usermail" value="{{ useremail }}" required>
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" placeholder="Enter your password" name="password" required>
          </div>
        </div>
        <div class="button">
          <input type="submit" value="Login">
        </div>
      </form>
      <form action="">{% csrf_token %}
        <div class="button">
          <a href="/"><input type="button" value="Main Page"></a>
        </div>
      </form>
    </div>
  </div>

</body>
</html>

web/templates/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Register </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src='https://www.google.com/recaptcha/api.js'></script>
   </head>
<body>
  <div class="container">
    <div class="title">Registration</div>
    <h1>{{ message }}</h1>
    <div class="content">
        
      <form action="." method="POST">{% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">Username</span>
            <input type="text" placeholder="Enter your username" name="username" value="{{ username }}" required>
          </div>
          <div class="input-box">
            <span class="details">Email</span>
            <input type="email" placeholder="Enter your email" name="email" value="{{ email }}" required>
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" placeholder="Enter your password" name="password" required>
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            <input type="password" placeholder="Confirm your password" name="passwordconf" required>
          </div>
        </div>
        <div class="input-box">
          <span class="details">Are you a robot?</span>
        </div>
        <!-- <div class="g-recaptcha" data-sitekey="6LeYJPAbAAAAADmiEwBulklBlykM6b2oOcfa9_VK"></div> -->
        <div class="g-recaptcha" data-sitekey="6LdGzfAbAAAAAHJeGJJ17wI_3Cw6s-k7jR9gPzfs"></div>
        
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
      <form action="">{% csrf_token %}
        <div class="button">
          <a href="/"><input type="button" value="Main Page"></a>
        </div>
      </form>
    </div>
  </div>

</body>
</html>

web/templates/tasks.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Tasks </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="title">Add New Task</div>
    <h1>{{ message }}</h1>
    <div class="content">
        
      <form action="/tasks/add/" method="POST">{% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">Task text</span>
            <input type="text" placeholder="Enter task text" name="text" class="edit" required>
          </div>
          <div class="input-box">
            <span class="details">Action date</span>
            <input type="date" name="action_date"class="edit" required>
          </div>
          <div class="input-box">
            <span class="details">Due date</span>
            <input type="date" name="due_date"class="edit" required>
          </div>
          <div class="input-box">
            <span class="details">Status</span>
            <select name="statuse" id="">
                <option value="Active">Active</option>
                <option value="Pending">Pending</option>
                <option value="Fail">Fail</option>
                <option value="Done">Done</option>
                <option value="Canceled">Canceled</option>
            </select>
          </div>
          <div class="input-box">
            <span class="details">Priority</span>
            <select name="priority" id="">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            </div>
        </div>
        
        <div class="button">
          <input type="submit" value="Add task">
        </div>
      </form>
    </div>
    <div>
      <div class="title">Here are your tasks</div>
        <table>
            <thead>
                <tr>
                    <th>taskText</th>
                    <th>priority</th>
                    <th>statuse</th>
                    <th>dueDate</th>
                    <th>actionDate</th>
                </tr>
                
            </thead>
            {% for item in task %}
            <tbody>
                <tr>
                    <td><a href="{{ item.get_url }}">{{ item.text }}</a></td>
                    <td><a href="{{ item.get_url }}">{{ item.priority }}</a></td>
                    <td><a href="{{ item.get_url }}">{{ item.statuse }}</a></td>
                    <td><a href="{{ item.get_url }}">{{ item.action_date|date:"Y-m-d" }}</a></td>
                    <td><a href="{{ item.get_url }}">{{ item.action_date }}</a></td>
                </tr>
            </tbody>
                {% endfor %}
        </table>
        <form action="">{% csrf_token %}
          <div class="button">
            <a href="{% url 'web:logout' %}"><input type="button" value="Logout"></a>
          </div>
        </form>
    </div>
  </div>

</body>
</html>

web/templates/tasks_edit.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Edit task </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="title">Edir your task</div>
    <h1>{{ message }}</h1>
    <div class="content">
        
        <form action="{{ task.get_edit_url }}" method="POST">{% csrf_token %}
            <div class="user-details">
              <div class="input-box">
                <span class="details">Task text</span>
                <input type="text" placeholder="Enter task text" name="text" value="{{ task.text }}" class="edit" required>
              </div>
              <div class="input-box">
                <span class="details">Action date</span>
                <input type="date" name="action_date"class="edit" value='{{ task.action_date|date:"Y-m-d" }}' required>
              </div>
              <div class="input-box">
                <span class="details">Due date</span>
                <input type="date" name="due_date"class="edit" value='{{ task.due_date|date:"Y-m-d" }}' required>
              </div>
              <div class="input-box">
                <span class="details">Status</span>
                <select name="statuse" id="">
                    {% if task.statuse == 'Active' %}
                    <option value="Active" selected>Active</option>
                    <option value="Pending">Pending</option>
                    <option value="Fail">Fail</option>
                    <option value="Done">Done</option>
                    <option value="Canceled">Canceled</option>
                    {% endif %}
                    {% if task.statuse == 'Pending' %}
                    <option value="Active">Active</option>
                    <option value="Pending" selected>Pending</option>
                    <option value="Fail">Fail</option>
                    <option value="Done">Done</option>
                    <option value="Canceled">Canceled</option>
                    {% endif %}
                    {% if task.statuse == 'Fail' %}
                    <option value="Active">Active</option>
                    <option value="Pending">Pending</option>
                    <option value="Fail" selected>Fail</option>
                    <option value="Done">Done</option>
                    <option value="Canceled">Canceled</option>
                    {% endif %}
                    {% if task.statuse == 'Done' %}
                    <option value="Active">Active</option>
                    <option value="Pending">Pending</option>
                    <option value="Fail">Fail</option>
                    <option value="Done" selected>Done</option>
                    <option value="Canceled">Canceled</option>
                    {% endif %}
                    {% if task.statuse == 'Canceled' %}
                    <option value="Active">Active</option>
                    <option value="Pending">Pending</option>
                    <option value="Fail">Fail</option>
                    <option value="Done">Done</option>
                    <option value="Canceled" selected>Canceled</option>
                    {% endif %}
                </select>
              </div>
              <div class="input-box">
                <span class="details">Priority</span>
                <select name="priority" id="">
                    {% if task.priority == '1' %}
                    <option value="1"  selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    {% endif %}
                    {% if task.priority == '2' %}
                    <option value="1">1</option>
                    <option value="2" selected>2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    {% endif %}
                    {% if task.priority == '3' %}
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3" selected>3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    {% endif %}
                    {% if task.priority == '4' %}
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4" selected>4</option>
                    <option value="5">5</option>
                    {% endif %}
                    {% if task.priority == '5' %}
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5" selected>5</option>
                    {% endif %}
                </select>
                </div>
            </div>
            
            <div class="button">
              <input type="submit" value="Edit task">
            </div>
          </form>
          <form action="{{ task.get_deleteConfirm_url }}" method="POST">{% csrf_token %}
            <div class="button">
              <input type="submit" value="Delete task">
            </div>
            <div class="button">
              <a href="{% url 'web:tasks' %}"><input type="button" value="Go Back"></a>
            </div>
          </form>
    </div>
  </div>

</body>
</html>